feature#14-franchises-screen-design
BrightCoders-Institute/BCDIC22-RN-proyecto-final-team2 pull request #19
Opened 2023-03-04 01:00 UTC by Manz1999

Implemented the corresponded design to the screen and installation of an external module for our ProductCard component

# Description
### What?
- Design and develop the design of the Franchises screen according to the proposed design. 
- See #14  for more information
### Why
- To organize the products according to the franchise
- To ensure the accorded design and bring the users the corresponding functionalities for the application. 
- See  #14 for more information.

## Testing

- Since the project is just initialized you only need install the basic packages to visualize the application
```npm install```
- then you can initialize with an android emulator or via web
```npm start```
-If you use expo
```npx expo start```

## Screenshots

| Proposed design   |      Successfull design      |
|----------|:-------------:|
| ![FRANCHISES](https://user-images.githubusercontent.com/102479612/222863847-11ad1a9b-59de-49d0-8219-85cf66e4f7a4.png) | |

2023-03-07 21:53 UTC, McFly1208 approved these changes

2023-03-07 21:54 UTC, EliasCode79 approved these changes

2023-03-07 21:56 UTC, arthurchina92 approved these changes
LGTM 🚀

2023-03-08 00:47 UTC, yovanha requested changes

2023-03-08 00:47 UTC, yovanha commented on src/screens/Categories/Franchises.jsx
> +// ];
Do you need this commented code?

2023-03-08 00:53 UTC, Manz1999 commented on src/screens/Categories/Franchises.jsx
> +// ];
No, I already deleted it.

2023-03-08 00:59 UTC, yovanha approved these changes

2023-03-08 00:59 UTC, merged