Product detail screen
BrightCoders-Institute/BCDIC22-RN-proyecto-final-team2 pull request #38
Opened 2023-03-18 01:29 UTC by garzo94

# Description

I implemented the product detail screen, this is a important feature to allow the users view all the details about the product that their are interested.
![Captura de pantalla (206)](https://user-images.githubusercontent.com/87275990/226075966-c5d544b1-bc23-4612-a300-c65b9f7a41c1.png)

2023-03-21 21:52 UTC, yovanha requested changes

2023-03-21 21:52 UTC, yovanha commented on src/screens/ProductDetail.jsx
> +        </CollapseHeader>
Please create a style file and move the styles your declaring on this component to that file, in order to separate logic from styles

2023-03-21 21:52 UTC, yovanha commented on src/screens/ProductDetail.jsx
> +            // color={COLORS.DARK_PURPLE}
Delete your comment code if you are not using it yet

2023-03-21 21:52 UTC, yovanha commented on src/screens/ProductDetail.jsx
> +              color: "#fff",
Use you library colors for this

2023-03-21 21:52 UTC, yovanha commented on src/styles/ProductDetail/ProductDetailStyle.jsx
> +    color: "#fff",
Please add this color to your library colors and call it here

2023-03-21 21:52 UTC, yovanha commented on src/styles/ProductDetail/ReviewsStyle.jsx
> +    backgroundColor: "rgba(255,255,255,0.5)",
Please add this to your library colors and call it here

2023-03-21 21:52 UTC, yovanha commented on src/styles/ProductDetail/ReviewsStyle.jsx
> +  description: { color: "rgba(255,255,255,0.7)", fontSize: 12 },
Please add this to your library colors

2023-03-22 01:13 UTC, IvanGodinez21 approved these changes

2023-03-22 02:04 UTC, yovanha approved these changes
💯

2023-03-22 16:21 UTC, beatrizheav approved these changes

2023-03-22 18:45 UTC, merged