Login - Register Screen Design Complete
BrightCoders-Institute/BCDIC22-RN-proyecto-final-team2 pull request #6
Opened 2023-02-20 23:19 UTC by QuackDuster

# Description
### What?
- Designed and created Login form component
- Designed and created Register form component
- Designed and created Login Tab Selector component
- Designed and recreated the design of the screen accorded to the proposed style. 
- See #3 for more information
### Why
- Design the screens accorded to the proposed design and ensure the functionalities of the application. See #3 for more information.

## Testing

- Since the project is just initialized you only need install the basic packages to visualize the application
```npm install```
- then you can initialize with an android emulator or via web
```npm start```

## Screenshots

| Proposed design   |      Successful design      |
|----------|:-------------:|
|![image](https://user-images.githubusercontent.com/54423116/220211513-e569ebcf-f279-467e-931a-72124787a539.png) | ![image](https://user-images.githubusercontent.com/54423116/220211553-031b4765-0e52-4e25-8c58-44ad4cdc4835.png) |
| ![image](https://user-images.githubusercontent.com/54423116/220211672-0de2d9d9-529b-4ca9-ae62-ca570f765c76.png)| ![image](https://user-images.githubusercontent.com/54423116/220211710-dad71aaa-9112-4f77-b2ca-2798f1180d6d.png) |

2023-02-20 23:28 UTC, IvanGodinez21 approved these changes
LGTM! 🐒

2023-02-20 23:36 UTC, Zuack55 approved these changes
good work

2023-02-20 23:38 UTC, Leonardo-Aguirre-Ponce approved these changes

2023-02-20 23:51 UTC, FloresEsme approved these changes

2023-02-21 00:12 UTC, yovanha requested changes

2023-02-21 00:12 UTC, yovanha commented on src/components/LoginForm.jsx
> +        <Text style={formLogin.hyperlink}>Register</Text>
It's more recomendable to use `Sign Up` instead of `Register`
```suggestion
        <Text style={formLogin.hyperlink}>Sign Up</Text>
```

2023-02-21 00:12 UTC, yovanha commented on src/components/LoginTabSelector.jsx
> +              <Text style={content.registerText}>Register</Text>
Same as above

2023-02-21 00:12 UTC, yovanha commented on src/styles/LoginScreen/Components_Login.jsx
> +    color: COLORS.GRAY,
Great work having your colors in another file 👌🏻

2023-02-21 00:12 UTC, yovanha commented on src/styles/LoginScreen/Components_Login.jsx
> +    marginBottom: 10,
Why do you have twice your `marginBottom`?

2023-02-21 00:12 UTC, yovanha commented on src/styles/LoginScreen/Components_Login.jsx
> +    fontWeight: '300',
Same as you have your colors in another file, it is a good practice to have your font-weights in a separate file calling them `lighter, medium, regular, or bold` depending on your needs.

2023-02-21 00:12 UTC, yovanha commented on src/styles/LoginScreen/Components_Login.jsx
> +    marginBottom: 10,
Same as above, you have twice your `marginBottom` style

2023-02-21 00:12 UTC, yovanha commented on src/styles/LoginScreen/Components_Login.jsx
> +  },
Here you are having duplicated code, could you please create a component for your inputs?

2023-02-21 00:12 UTC, yovanha commented on src/styles/LoginScreen/Components_Register.jsx
> +  },
Same here, you could save some lines if you create an input component for your three inputs and just share as a prop the deferents names of each one

2023-02-21 00:12 UTC, yovanha commented on src/styles/colors.jsx
> +};
Really good job here! Let's make the same for your font-weights 👍🏻

2023-02-21 01:36 UTC, yovanha approved these changes
Good job! 👏

2023-02-21 03:03 UTC, merged