Greeting Screen Design Complete
BrightCoders-Institute/BCDIC22-RN-proyecto-final-team2 pull request #7
Opened 2023-02-22 01:05 UTC by Manz1999

# Description
### What?
- Designed and created Greeting Screen
- Designed and recreated the design of the screen accorded to the proposed style. 
- See #4  for more information
### Why
- Design the screens accorded to the proposed design and ensure the functionalities of the application. See #4 for more information.

## Testing

- Since the project is just initialized you only need install the basic packages to visualize the application
```npm install```
- then you can initialize with an android emulator or via web
```npm start```
- or if you use expo
```npx expo start```

## Screenshots

| Proposed design   |      Successfull design      |
|----------|:-------------:|
| ![proposed](https://user-images.githubusercontent.com/102479612/220492917-8fc82eaf-80f3-488a-b056-b2e076406c65.png) | ![succesfull](https://user-images.githubusercontent.com/102479612/220494089-473defd7-d710-4680-83af-034dde1dcf0b.png)|

2023-02-22 19:53 UTC, yovanha approved these changes, later dismissed

2023-02-22 19:53 UTC, yovanha commented on src/styles/GreetingScreen/Screen_Greeting.jsx
> +  },
You have here duplicated code, lets use the text1 styles in your tex2 and just add the marginLeft style to `text2`

2023-02-22 19:53 UTC, yovanha commented on src/styles/GreetingScreen/Screen_Greeting.jsx
> +    color: 'white',
You have this color in your library colors, could you please add it here?

2023-02-22 19:53 UTC, yovanha commented on src/styles/GreetingScreen/Screen_Greeting.jsx
> +    color: 'darkslateblue',
Do you have this color in you library colors?

2023-02-22 19:53 UTC, yovanha commented on src/styles/LoginScreen/Components_Login.jsx
>      top: 15,
Is there a reason why did you delete the code which you already refactored?

2023-02-22 19:53 UTC, yovanha commented on src/styles/LoginScreen/Components_Register.jsx
> +  },
Could you please refactor this? I see you have the same props but you're just changing the bottom and top styles

2023-02-22 19:55 UTC, yovanha requested changes
Requested changes

2023-02-22 23:31 UTC, Matarratas777 approved these changes
LGTM🍆

2023-02-22 23:37 UTC, arthurchina92 approved these changes
🚀

2023-02-22 23:37 UTC, IvanGodinez21 approved these changes

2023-02-23 00:07 UTC, FloresEsme approved these changes

2023-02-23 19:10 UTC, yovanha approved these changes

2023-02-23 20:43 UTC, merged